In [1]:
import pandas as pd
import numpy as np

In [4]:
animals=['tiger','cat','dog']
r=pd.Series(animals)
r,r.dtype

(0    tiger
 1      cat
 2      dog
 dtype: object, dtype('O'))

In [6]:
numbers=[1,2,3]
pd.Series(numbers).dtype

dtype('int64')

In [7]:
import pandas as pd
pd.read_csv('DataFiles/olympics.csv')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
6,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
7,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
8,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
9,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
10,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
11,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
12,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
13,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
14,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
15,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
16,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
17,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
18,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
19,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
20,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
21,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
22,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
23,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
24,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
25,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
26,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
27,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
28,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
29,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
119,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
120,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
121,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
122,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
123,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
124,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
125,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
126,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
127,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
128,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
129,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
130,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
131,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
132,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
133,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
134,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
135,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
136,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
137,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [8]:
p=pd.read_csv('DataFiles/olympics.csv')
p.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [9]:
p.tail(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [10]:
p.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [16]:
df=pd.read_csv('DataFiles/olympics.csv',index_col=0,skiprows=1)
df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [22]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' +col[4:]},inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' +col[4:]},inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' +col[4:]},inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' +col[1:]},inplace=True)
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [25]:
only_gold=df.where(df['Gold']>0)
only_gold.head()
len(only_gold)

147

In [26]:
only_gold=df[df['Gold']>0]
only_gold

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Denmark (DEN) [Z],26,43,68,68,179,13,0,1,0,1,39,43,69,68,180
Dominican Republic (DOM),13,3,2,1,6,0,0,0,0,0,13,3,2,1,6
Ecuador (ECU),13,1,1,0,2,0,0,0,0,0,13,1,1,0,2
Egypt (EGY) [EGY] [Z],21,7,9,10,26,1,0,0,0,0,22,7,9,10,26
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Ethiopia (ETH),12,21,7,17,45,2,0,0,0,0,14,21,7,17,45
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Russian Empire (RU1) [RU1],3,1,4,3,8,0,0,0,0,0,3,1,4,3,8
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Serbia (SRB) [SRB],3,1,2,4,7,2,0,0,0,0,5,1,2,4,7
Serbia and Montenegro (SCG) [SCG],3,2,4,3,9,3,0,0,0,0,6,2,4,3,9
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
South Africa (RSA),18,23,26,27,76,6,0,0,0,0,24,23,26,27,76
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [27]:
df[df['Gold']<5]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
Djibouti (DJI) [B],7,0,0,1,1,0,0,0,0,0,7,0,0,1,1
Dominican Republic (DOM),13,3,2,1,6,0,0,0,0,0,13,3,2,1,6
Ecuador (ECU),13,1,1,0,2,0,0,0,0,0,13,1,1,0,2
Eritrea (ERI),4,0,0,1,1,0,0,0,0,0,4,0,0,1,1
Gabon (GAB),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Ghana (GHA) [GHA],13,0,1,3,4,1,0,0,0,0,14,0,1,3,4
Grenada (GRN),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
Guatemala (GUA),13,0,1,0,1,1,0,0,0,0,14,0,1,0,1
Guyana (GUY) [GUY],16,0,0,1,1,0,0,0,0,0,16,0,0,1,1
Haiti (HAI) [J],14,0,1,1,2,0,0,0,0,0,14,0,1,1,2
Hong Kong (HKG) [HKG],15,1,1,1,3,4,0,0,0,0,19,1,1,1,3
Iceland (ISL),19,0,2,2,4,17,0,0,0,0,36,0,2,2,4
Iraq (IRQ),13,0,0,1,1,0,0,0,0,0,13,0,0,1,1
Israel (ISR),15,1,1,5,7,6,0,0,0,0,21,1,1,5,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Portugal (POR),23,4,8,11,23,7,0,0,0,0,30,4,8,11,23
Puerto Rico (PUR),17,0,2,6,8,6,0,0,0,0,23,0,2,6,8
Qatar (QAT),8,0,0,4,4,0,0,0,0,0,8,0,0,4,4
Russian Empire (RU1) [RU1],3,1,4,3,8,0,0,0,0,0,3,1,4,3,8
Saudi Arabia (KSA),10,0,1,2,3,0,0,0,0,0,10,0,1,2,3
Senegal (SEN),13,0,1,0,1,5,0,0,0,0,18,0,1,0,1
Serbia (SRB) [SRB],3,1,2,4,7,2,0,0,0,0,5,1,2,4,7
Serbia and Montenegro (SCG) [SCG],3,2,4,3,9,3,0,0,0,0,6,2,4,3,9
Singapore (SIN),15,0,2,2,4,0,0,0,0,0,15,0,2,2,4
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8

In [31]:
s=df[(df['Gold']>0)|(df['Gold.1']>0)]
s['Gold'].count

<bound method Series.count of Algeria (ALG)                             5
Argentina (ARG)                          18
Armenia (ARM)                             1
Australasia (ANZ) [ANZ]                   3
Australia (AUS) [AUS] [Z]               139
Austria (AUT)                            18
Azerbaijan (AZE)                          6
Bahamas (BAH)                             5
Belarus (BLR)                            12
Belgium (BEL)                            37
Brazil (BRA)                             23
Bulgaria (BUL) [H]                       51
Burundi (BDI)                             1
Cameroon (CMR)                            3
Canada (CAN)                             59
Chile (CHI) [I]                           2
China (CHN) [CHN]                       201
Colombia (COL)                            2
Costa Rica (CRC)                          1
Croatia (CRO)                             6
Cuba (CUB) [Z]                           72
Czech Republic (CZE) [CZE]               14
Czechoslovakia (TCH) [TCH]               49
Denmark (DEN) [Z]                        43
Dominican Republic (DOM)                  3
Ecuador (ECU)                             1
Egypt (EGY) [EGY] [Z]                     7
Estonia (EST)                             9
Ethiopia (ETH)                           21
Finland (FIN)                           101
                                       ...
Russia (RUS) [RUS]                      132
Russian Empire (RU1) [RU1]                1
Soviet Union (URS) [URS]                395
Unified Team (EUN) [EUN]                 45
Serbia (SRB) [SRB]                        1
Serbia and Montenegro (SCG) [SCG]         2
Slovakia (SVK) [SVK]                      7
Slovenia (SLO)                            4
South Africa (RSA)                       23
Spain (ESP) [Z]                          37
Suriname (SUR) [E]                        1
Sweden (SWE) [Z]                        143
Switzerland (SUI)                        47
Syria (SYR)                               1
Chinese Taipei (TPE) [TPE] [TPE2]         2
Thailand (THA)                            7
Trinidad and Tobago (TRI) [TRI]           2
Tunisia (TUN)                             3
Turkey (TUR)                             39
Uganda (UGA)                              2
Ukraine (UKR)                            33
United Arab Emirates (UAE)                1
United States (USA) [P] [Q] [R] [Z]     976
Uruguay (URU)                             2
Uzbekistan (UZB)                          5
Venezuela (VEN)                           2
Yugoslavia (YUG) [YUG]                   26
Zimbabwe (ZIM) [ZIM]                      3
Mixed team (ZZX) [ZZX]                    8
Totals                                 4809
Name: Gold, Length: 101, dtype: int64>

In [33]:
df[(df['Gold.1']>0)&(df['Gold']>0)]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
France (FRA) [O] [P] [Z],27,202,223,246,671,22,31,31,47,109,49,233,254,293,780
Germany (GER) [GER] [Z],15,174,182,217,573,11,78,78,53,209,26,252,260,270,782
United Team of Germany (EUA) [EUA],3,28,54,36,118,3,8,6,5,19,6,36,60,41,137
East Germany (GDR) [GDR],5,153,129,127,409,6,39,36,35,110,11,192,165,162,519
West Germany (FRG) [FRG],5,56,67,81,204,6,11,15,13,39,11,67,82,94,243
Great Britain (GBR) [GBR] [Z],27,236,272,272,780,22,10,4,12,26,49,246,276,284,806
Italy (ITA) [M] [S],26,198,166,185,549,22,37,34,43,114,48,235,200,228,663
Japan (JPN),21,130,126,142,398,20,10,17,18,45,41,140,143,160,443
Kazakhstan (KAZ),5,16,17,19,52,6,1,3,3,7,11,17,20,22,59
South Korea (KOR),16,81,82,80,243,17,26,17,10,53,33,107,99,90,296
Netherlands (NED) [Z],25,77,85,104,266,20,37,38,35,110,45,114,123,139,376
Norway (NOR) [Q],24,56,49,43,148,22,118,111,100,329,46,174,160,143,477
Poland (POL),20,64,82,125,271,22,6,7,7,20,42,70,89,132,291
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579